---
- name: Setup bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup.yaml

    - name: Import VPC variables
      include_vars: vars/output_vars

    - name: Create key pair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: SSH from anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: BastionSG_out

    - name: Create bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out

    - name: Add BastionSGid variable to vars/output_vars
      blockinfile:
        path: vars/output_vars
        backup: no
        block: |
          BastionSGid: {{BastionSG_out.group_id}}