---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Import vprofile setup Variable
      include_vars: vars/vprostacksetup

    - name: Create vprofile key pair
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: Create security group for ELB
      ec2_group:
        name: vproELB-sg
        description: Allow http from anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: Create security group for vprofile stack
      ec2_group:
        name: vproStack-sg
        description: Allow HTTP from ELB SG and SSH from bastion SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
        - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{vproELBSG_out.group_id}}"
        - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{BastionSGid}}"
      register: vproStackSG_out

    - name: Update security group with its own id
      ec2_group:
        name: vproStack-sg
        description: Allow all connections from within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
        - proto: all
          group_id: "{{vproStackSG_out.group_id}}"